services:
  mysql:
    image: mysql
    container_name: inflearn-clone-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - inflearn_clone_db:/var/lib/mysql
volumes:
  inflearn_clone_db:
